"""Added priority column to Task model

Revision ID: d47a1e0d2103
Revises: 
Create Date: 2025-01-28 18:15:21.435911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd47a1e0d2103'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deadline_date', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('deadline_time', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('deadline_time')
        batch_op.drop_column('deadline_date')

    # ### end Alembic commands ###
